//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OECS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Module()
        {
            this.RoleModule = new HashSet<RoleModule>();
            this.SubModule = new HashSet<SubModule>();
        }
    
        public int ModuleID { get; set; }
        public string module1 { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string icon { get; set; }
        public Nullable<bool> hasArrow { get; set; }
        public Nullable<bool> hasChild { get; set; }
        public Nullable<int> orderBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleModule> RoleModule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubModule> SubModule { get; set; }
    }
}
