//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OECS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> CreditCardNumber { get; set; }
        public Nullable<System.DateTime> CreditCardExpirationDate { get; set; }
        public string CardHoldersName { get; set; }
        public string OrderNumber { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
