//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OECS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductImage()
        {
            this.DisplayColor = new HashSet<DisplayColor>();
            this.DisplaySize = new HashSet<DisplaySize>();
        }
    
        public int ProductImageID { get; set; }
        public int ProductDetailID { get; set; }
        public Nullable<int> ImageID { get; set; }
        public Nullable<bool> isMainDisplay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisplayColor> DisplayColor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisplaySize> DisplaySize { get; set; }
        public virtual Image Image { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
