//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OECS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int ImageID { get; set; }
        public string path { get; set; }
        public Nullable<int> ProductColorID { get; set; }
        public Nullable<bool> isMainDisplay { get; set; }
        public Nullable<int> IconID { get; set; }
    
        public virtual Icon Icon { get; set; }
        public virtual ProductColor ProductColor { get; set; }
    }
}
